{{- if (include "radar-upload-connect-backend.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.postgres.urlSecret }}
    {{- $port := .Values.postgres.port | default "5432" }}
    {{- $url := printf "jdbc:postgresql://%s:%s/%s" .Values.postgres.host $port .Values.postgres.database }}
    {{- if .Values.postgres.parameters }}
  databaseUrl: {{ printf "%s?%s" $url .Values.postgres.parameters | b64enc | quote }}
    {{- else }}
  databaseUrl: {{ $url | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- if not .Values.postgres.userSecret }}
  databaseUser: {{ .Values.postgres.user | b64enc | quote }}
  {{- end }}
  {{- if not .Values.postgres.passwordSecret }}
  databasePassword: {{ .Values.postgres.password | b64enc | quote }}
  {{- end }}
{{- end }}
