apiVersion: v2
name: radar-cloudnative-timescaledb
version: 0.2.1
description: CloudNativePG timescaledb cluster helm chart for RADAR-base
maintainers:
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
dependencies:
  - name: cluster
    version: 0.2.1
    repository: file://../../external/cloudnative-pg/cluster
