{{- if .Values.secret.enabled }}
{{- $host := printf "%s-cluster-rw.default" $.Release.Name }}
{{- $port := "5432" }}
{{- range .Values.secret.users }}
---
{{- $secretName := printf "%s-%s" (include "radar-cloudnativepg-postgresql.secretname" $) .user }}
{{- $password := include "radar-cloudnativepg-postgresql.secret.value" (dict "secret" $secretName "key" "password" "context" $) | default (randAlphaNum 65) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    cnpg.io/reload: "true"
  {{- if or $.Values.commonAnnotations $.Values.secret.secretAnnotations }}
  annotations:
  {{- if $.Values.commonAnnotations }}
  {{- include "common.tplvalues.render" (dict "value" $.Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
  {{- if $.Values.secret.secretAnnotations }}
  {{- include "common.tplvalues.render" (dict "value" $.Values.secret.secretAnnotations "context" $) | nindent 4 }}
  {{- end }}
  {{- end }}
type: kubernetes.io/basic-auth
data:
  name: {{ .user | b64enc | quote }}
  username: {{ .user | b64enc | quote }}
  password: {{ $password | b64enc | quote}}
  dbname: {{ .dbname | b64enc | quote }}
  host: {{ $host | b64enc | quote }}
  port: {{ $port | b64enc }}
  uri: {{ (printf "postgresql://%s:%s@%s:%s/%s" .user $password $host $port .dbname) | b64enc | quote }}
  jdbc-uri: {{ (printf "jdbc:postgresql://%s:%s/%s?password=%s&user=%s" $host $port .dbname $password .user) | b64enc | quote }}
{{- end }}
{{- end }}
