{{- $top := . }}
{{- $host := printf "%s-cluster-rw.default" $top.Release.Name }}
{{- $port := "5432" }}
{{- range .Values.secrets }}
---
{{- $secretName := printf "%s-%s" $top.Release.Name .user }}
{{- $password := (include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "password" "length" 65 "providedValues" (list ) "skipQuote" "true" "skipB64enc" "true" "context" $top)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  name: {{ .user | b64enc | quote }}
  username: {{ .user | b64enc | quote }}
  password: {{ $password | b64enc | quote}}
  dbname: {{ .dbname | b64enc | quote }}
  host: {{ $host | b64enc | quote }}
  port: {{ $port | b64enc }}
  uri: {{ (printf "postgresql://%s:%s@%s:%s/%s" .user $password $host $port .dbname) | b64enc | quote }}
  jdbc-uri: {{ (printf "jdbc:postgresql://%s:%s/%s?password=%s&user=%s" $host $port .dbname $password .user) | b64enc | quote }}
{{ end }}
