apiVersion: v2
appVersion: v1.3.0
dependencies:
- alias: ory
  name: ory-commons
  repository: file://../ory-commons
  version: 0.1.0
description: A ORY Kratos Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-kratos.svg
name: kratos
type: application
version: 0.52.1
