apiVersion: v2
appVersion: "4.48"
description: SeaweedFS S3-compatible object storage for RADAR-base, deployed via the SeaweedFS operator. Alternative to MinIO.
name: radar-seaweedfs
home: "https://radar-base.org"
version: 0.1.0
icon: "http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png"
sources:
  - https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-seaweedfs
  - https://github.com/seaweedfs/seaweedfs
  - https://github.com/seaweedfs/seaweedfs-operator
maintainers:
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
type: application
keywords:
  - seaweedfs
  - s3
  - object-storage
dependencies:
  - name: common
    repository: https://radar-base.github.io/radar-helm-charts
    tags:
      - bitnami-common
    version: 2.x.x
