apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ if .Values.cc.enabled -}}
  {{- $jaasConfig := print `org.apache.kafka.common.security.plain.PlainLoginModule required username="` .Values.cc.apiKey `" password="` .Values.cc.apiSecret `";` }}
  schemaRegistryCredential: {{ print .Values.cc.schemaRegistryApiKey ":" .Values.cc.schemaRegistryApiSecret | b64enc | quote }}
  kafkaSaslJaasConfig: {{ $jaasConfig | b64enc | quote }}
  {{- end }}
  {{- if and .Values.bucketAccessKey .Values.bucketSecretKey }}
  awsAccessKey: {{ .Values.bucketAccessKey | b64enc | quote }}
  awsSecretKey: {{ .Values.bucketSecretKey | b64enc | quote }}
  {{- end }}
