apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    # Kafka
    kafka:
      {{- range $key, $value := .Values.kafkaProperties }}
      {{ $key | replace "_" "." }}: {{ $value }}
      {{- end }}
      {{- if .Values.cc.enabled }}
      bootstrap.servers: {{ .Values.cc.bootstrapServerurl }}
      security.protocol: SASL_SSL
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      {{- end }}

    sources:
      {{- toYaml .Values.sources | nindent 6 }}

    schemas:
      {{- toYaml .Values.schemas | nindent 6 }}

    topics:
      {{- toYaml .Values.topics | nindent 6 }}
