{{- if .Values.cc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  ccApiKey: {{ .Values.cc.apiKey | b64enc | quote }}
  ccApiSecret: {{ .Values.cc.apiSecret | b64enc | quote }}
  srApiKey: {{ .Values.cc.schemaRegistryApiKey | b64enc | quote }}
  srApiSecret: {{ .Values.cc.schemaRegistryApiSecret | b64enc | quote }}
  saslJaasConfig: {{ template "catalog-server.saslJaasConfig" .Values.cc }}
{{- end -}}
