apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar-output.fullname" . }}
  labels:
{{ include "radar-output.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-output.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if not .Values.existingSecret }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "radar-output.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - {{ template "radar-output.name" . }}
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                    - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: output
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - radar-output-restructure
          args:
            - -F
            - /etc/radar-output/config.yaml
          env:
          - name: RADAR_OUTPUT_RESTRUCTURE_OPTS
            value: {{ .Values.javaOpts  | quote }}
          - name: SOURCE_S3_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: sourceS3AccessToken
          - name: SOURCE_S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: sourceS3SecretKey
          - name: TARGET_S3_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: targetS3AccessToken
          - name: TARGET_S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: targetS3SecretKey
          - name: SOURCE_AZURE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: sourceAzureUsername
          - name: SOURCE_AZURE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: sourceAzurePassword
          - name: SOURCE_AZURE_ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: sourceAzureAccountName
          - name: SOURCE_AZURE_ACCOUNT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: sourceAzureAccountKey
          - name: SOURCE_AZURE_SAS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: sourceAzureSasToken
          - name: TARGET_AZURE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: targetAzureUsername
          - name: TARGET_AZURE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: targetAzurePassword
          - name: TARGET_AZURE_ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: targetAzureAccountName
          - name: TARGET_AZURE_ACCOUNT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: targetAzureAccountKey
          - name: TARGET_AZURE_SAS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-output.secretName" . }}
                key: targetAzureSasToken
          {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath:  /etc/radar-output
      volumes:
        - name: config
          configMap:
            name: {{ include "radar-output.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
