image:
  # -- Image registry
  registry: quay.io
  # -- Image repository
  repository: opstree/redis
  # -- Image tag (immutable tags are recommended)
  # Overrides the image tag whose default is the chart appVersion.
  tag:
  # -- Image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
  digest: ""
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # e.g:
  # pullSecrets:
  #   - myRegistryKeySecretName
  #
  pullSecrets: []

# -- Can be 'standalone' or 'replication'
mode: standalone

replication:
  # -- Number of replicated redis nodes
  replicates: 3
  resources:
    # -- resource requests for redis pods
    requests:
      cpu: 101m
      memory: 128Mi
    # -- resource limits for redis pods
    limits:
      cpu: 101m
      memory: 128Mi

standalone:
  resources:
    # -- resource requests for redis pods
    requests:
      cpu: 101m
      memory: 128Mi
    # -- resource limits for redis pods
    limits:
      cpu: 101m
      memory: 128Mi

storage:
  # -- Access mode for PVC
  accessModes:
    - ReadWriteOnce
  # -- Size of PVC
  size: 1Gi

# -- Security context for redis pods
securityContext:
  runAsUser: 1000
  fsGroup: 1000
