apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  healthcheck.sh: |
    #!/bin/sh
    STATUS=$(curl -s --max-time 4 localhost:8090/appconfig/api/health)
    if ! (echo "$STATUS" | grep -Fq 'db":{"status":"UP'); then
      exit 1
    fi
  appconfig.yml: |
    baseUri: http://0.0.0.0:8090/appconfig/api
    isJmxEnabled: false

    inject:
      enhancerFactory: org.radarbase.appconfig.inject.ManagementPortalEnhancerFactory

    auth:
      managementPortal:
        url: {{ .Values.managementportal_url }}
      jwtResourceName: res_appconfig

    database:
      driver: {{ .Values.jdbc.driver }}
      dialect: {{ .Values.jdbc.dialect }}

    hazelcast:
      network:
        port: 5801
        join:
          multicastConfig:
            enabled: false
          kubernetesConfig:
            enabled: true
            properties:
              service-name: {{ template "app-config.fullname" . }}
              service-port: 5801
              namespace: {{ .Values.namespace }}
