apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}-hazelcast
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: hazelcast
    targetPort: hazelcast
    protocol: TCP
    port: 5801
  selector:
    app.kubernetes.io/name: {{ include "app-config.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
