{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # Generate a random secret if the user doesn't give one. User given secret has priority
  {{- $cookieSecretName := printf "%s-%s" (include "common.names.fullname" .) "csrf-cookie" }}
  {{- $cookieSecret := include "common.secrets.passwords.manage" (dict "secret" $cookieSecretName "key" "cookieSecret" "providedValues" (list ) "length" 32 "skipQuote" "true" "skipB64enc" "true" "context" $) }}
  {{- $cookieCsrfSecret := include "common.secrets.passwords.manage" (dict "secret" $cookieSecretName "key" "cookieCsrfSecret" "providedValues" (list ) "length" 32 "skipQuote" "true" "skipB64enc" "true" "context" $) }}
  secretsCookie: {{ ( .Values.config.secrets.cookie | default $cookieSecret) | required "Value config.secrets.cookie can not be empty!" | b64enc | quote }}
  secretsCSRFCookie: {{ ( .Values.config.secrets.csrfCookie | default $cookieCsrfSecret) | required "Value config.secrets.csrfCookie can not be empty!" | b64enc | quote }}
{{- end }}
