{{- if .Values.secret.enabled -}}
{{- $secretName := include "radar-self-enrolment-ui.secretname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.secret.secretAnnotations }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.secret.secretAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.secret.secretAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- end }}
type: Opaque
data:
  {{- $secretsCookie := include "radar-self-enrolment-ui.secret.value" (dict "secret" $secretName "key" "secretsCookie" "context" .) | default (randAlphaNum 32) }}
  secretsCookie: {{ ( .Values.config.secrets.cookie | default $secretsCookie) | b64enc | quote }}
  {{- $secretsCSRFCookie := include "radar-self-enrolment-ui.secret.value" (dict "secret" $secretName "key" "secretsCSRFCookie" "context" .) | default (randAlphaNum 32) }}
  secretsCSRFCookie: {{ ( .Values.config.secrets.csrfCookie | default $secretsCSRFCookie) | b64enc | quote }}
{{- end }}
