apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-object-storage-backup
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.objectStorageBackupReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "velero-s3-deployment.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "velero-s3-deployment.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- include "velero-s3-deployment.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: intermediate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "velero-s3-deployment.image" . }}
          imagePullPolicy: {{ .Values.mc_image.pullPolicy | quote }}
          env:
          - name: MC_HOST_local
            value: "http://{{ .Values.local.accessKey }}:{{ .Values.local.secretKey }}@{{ .Values.local.address }}"
          - name: MC_HOST_backup
            value: "https://{{ .Values.backup.accessKey }}:{{ .Values.backup.secretKey }}@{{ .Values.backup.address }}"
          command:
            - mc
            - mirror
            - --overwrite
            - --watch
            - --md5
            - local/{{ .Values.local.intermediateBucketName }}
            - backup/{{ .Values.backup.intermediateBucketName }}
        - name: output
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "velero-s3-deployment.image" . }}
          imagePullPolicy: {{ .Values.mc_image.pullPolicy | quote }}
          env:
          - name: MC_HOST_local
            value: "http://{{ .Values.local.accessKey }}:{{ .Values.local.secretKey }}@{{ .Values.local.address }}"
          - name: MC_HOST_backup
            value: "https://{{ .Values.backup.accessKey }}:{{ .Values.backup.secretKey }}@{{ .Values.backup.address }}"
          command:
            - mc
            - mirror
            - --overwrite
            - --watch
            - --md5
            - local/{{ .Values.local.outputBucketName }}
            - backup/{{ .Values.backup.outputBucketName }}
