
{{- if or .Values.connections .Values.additionalPIPPackages }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-airflow-custom-env
  labels:
    app.kubernetes.io/name: radar-airflow
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{- if .Values.additionalPIPPackages }}
  _PIP_ADDITIONAL_REQUIREMENTS: {{ join " " .Values.additionalPIPPackages | quote }}
  {{- end }}
  {{- range .Values.connections }}
  {{- $connId := regexReplaceAll "[^A-Za-z0-9]" (.id | upper) "_" }}
  {{- if .uri }}
  AIRFLOW_CONN_{{ $connId }}: {{ .uri | quote }}
  {{- else if hasKey . "json" }}
  {{- if kindIs "string" .json }}
  AIRFLOW_CONN_{{ $connId }}: {{ .json | quote }}
  {{- else }}
  AIRFLOW_CONN_{{ $connId }}: {{ .json | toJson | quote }}
  {{- end }}
  {{- else if hasKey . "config" }}
  {{- if kindIs "string" .config }}
  AIRFLOW_CONN_{{ $connId }}: {{ .config | quote }}
  {{- else }}
  {{- $meta := omit . "id" "uri" "json" "config" }}
  {{- $payload := merge (dict) $meta .config }}
  AIRFLOW_CONN_{{ $connId }}: {{ $payload | toJson | quote }}
  {{- end }}
  {{- else }}
  {{- $payload := omit . "id" "uri" "json" "config" }}
  AIRFLOW_CONN_{{ $connId }}: {{ $payload | toJson | quote }}
  {{- end }}
  {{- end }}
{{- end }}
