apiVersion: v2
name: radar-cloudnative-postgresql
version: 0.2.1
description: CloudNativePG postgresql helm chart for RADAR-base
maintainers:
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
dependencies:
- name: cluster
  repository: https://cloudnative-pg.github.io/charts
  version: 0.2.1
- name: common
  repository: https://radar-base.github.io/radar-helm-charts
  tags:
  - bitnami-common
  version: 2.x.x
