{{ $context := .Values.kafka }}
{{- $replicationFactor := ternary 1 $context.replicas .Values.dev_deployment -}}
{{- $insyncReplicas := ternary 1 $context.insyncReplicas .Values.dev_deployment -}}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  kafka:
    version: {{ .Chart.AppVersion }}
    metadataVersion: {{ .Values.metadataVersion }}
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: {{ $replicationFactor }}
      transaction.state.log.replication.factor: {{ $replicationFactor }}
      transaction.state.log.min.isr: {{ $insyncReplicas }}
      default.replication.factor: {{ $replicationFactor }}
      min.insync.replicas: {{ $insyncReplicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: scram
        port: 9094
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
  {{- if .Values.metrics.enabled }}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: {{ template "common.names.fullname" . }}-kafka-metrics
          key: kafka-metrics-config.yml
  kafkaExporter:
    {{- toYaml .Values.metrics.kafkaExporter | nindent 4 }}
  {{- end }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
