{{ $context := .Values.kafka }}
{{- $replicas := ternary 1 $context.replicas .Values.dev_deployment }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    strimzi.io/cluster: {{ template "common.names.fullname" . }}
spec:
  replicas: {{ $replicas }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        {{- if .Values.dev_deployment }}
        type: ephemeral
        kraftMetadata: shared
        {{- else }}
        type: persistent-claim
        size: {{ $context.storage.size }}
        deleteClaim: false
        kraftMetadata: shared
        {{- end }}
