{{- $context := index .Values "schema-registry" "topic" }}
{{/*use 3 as max replication factor; use 1 when in dev mode*/}}
{{- $topicReplicationFactor := min 3 (ternary 1 $context.replicationFactor .Values.dev_deployment) }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  # IMPORTANT: do not rename, must be named 'registry-schemas'
  name: registry-schemas
  labels:
    strimzi.io/cluster: {{ template "common.names.fullname" . }}
spec:
{{/*  TODO when changing partitions on this getting: "The schema topic registry-schemas should have only 1 partition but has 3" */}}
{{/*  According to https://stackoverflow.com/a/74777178 schema topic should not have more than 1 partition */}}
  partitions: {{ $context.partitions }}
  replicas: {{ $topicReplicationFactor }}
  config:
    {{- toYaml $context.config | nindent 4 }}
