apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
{{/*    TODO we need to revert this back to 'true'*/}}
    strimzi.io/use-connector-resources: "false"
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  version: {{ .Chart.AppVersion }}
  replicas: {{ .Values.replicaCount }}
  bootstrapServers: {{ .Values.kafka }}
  image: {{ template "radar-s3-connector.image" . }}
  {{- if .Values.secret.jaas.name }}
  # Authentication-related props are handled by the template builder in https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectConfigurationBuilder.java
  authentication:
    type: scram-sha-512
    username: shared-service-user
    passwordSecret:
      secretName: {{ .Values.secret.jaas.name }}
      password: password # The name of the key in the secret that contains the password
  {{- else if .Values.cc.enabled }}
  authentication:
    type: scram-sha-512
    username: {{ .Values.cc.apiKey | quote }}
    passwordSecret:
      secretName: {{ template "common.names.fullname" . }}
      password: ccJaasPassword
  {{- end }}
  autoRestart:
    enabled: true # automatic restarts of failed connectors or their tasks
  jvmOptions:
    "-Xmx": {{ .Values.jvmOptions.xmx | quote }}
    "-Xms": {{ .Values.jvmOptions.xms | quote }}
  config: # Properties that configure the Kafka Connect cluster itself
    group.id: {{ include "common.names.fullname" . }}
    offset.storage.topic: {{ template "common.names.fullname" . }}.offset
    config.storage.topic: {{ template "common.names.fullname" . }}.config
    status.storage.topic: {{ template "common.names.fullname" . }}.status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    key.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    {{- if .Values.cc.enabled }}
    key.converter.schema.registry.url: {{ .Values.cc.schemaRegistryUrl }}
    key.converter.basic.auth.credentials.source: USER_INFO
    key.converter.basic.auth.user.info: {{ .Values.cc.schemaRegistryApiKey }}:{{ .Values.cc.schemaRegistryApiSecret }}
    value.converter.schema.registry.url: {{ .Values.cc.schemaRegistryUrl }}
    value.converter.basic.auth.credentials.source: USER_INFO
    value.converter.basic.auth.user.info: {{ .Values.cc.schemaRegistryApiKey }}:{{ .Values.cc.schemaRegistryApiSecret }}
    {{- else }}
    key.converter.schema.registry.url: {{ .Values.schema_registry }}
    value.converter.schema.registry.url: {{ .Values.schema_registry }}
    {{- end }}
    flush.size: {{ .Values.flushSize | int }}
    connect.meta.data: false
  template:
    pod:
      metadata:
        annotations:
          checksum/configmap-log4j: {{ include (print $.Template.BasePath "/configmap-log4j.yaml") . | sha256sum }}
          backup.velero.io/backup-volumes: logs
        labels:
          app.kubernetes.io/name: {{ include "common.names.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
      imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        {{- if .Values.affinity }}
        {{- toYaml .Values.affinity | nindent 8 }}
        {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - {{ template "common.names.name" . }}
                    - key: "app.kubernetes.io/instance"
                      operator: In
                      values:
                        - {{ .Release.Name }}
                topologyKey: "kubernetes.io/hostname"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
    connectContainer:
      env:
        {{- if and .Values.bucketAccessKey .Values.bucketSecretKey }}
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "common.names.fullname" . }}
              key: awsAccessKey
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "common.names.fullname" . }}
              key: awsSecretKey
        {{- end }}
        - name: CONNECT_REST_ADVERTISED_HOST_NAME  # Possibly replaced by ADVERTISED_HOSTNAME in kafka_connect_run.sh
          value: {{ include "common.names.fullname" . }}
        - name: KAFKA_LOG4J_OPTS
          value: "-Dlog4j.configuration=file:/opt/kafka/custom-config/log4j.properties"
        {{- if .Values.sentry.dsn }}
        - name: SENTRY_DSN
          value: {{ .Values.sentry.dsn | quote }}
        - name: SENTRY_LOG_LEVEL
          value: {{ .Values.sentry.level | quote }}
        {{- end }}
        {{- with .Values.extraEnvVars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
  logging:
    type: external
    valueFrom:
      configMapKeyRef:
        name: {{ template "common.names.fullname" . }}-log4j
        key: log4j.properties
  {{- if .Values.customLivenessProbe }}
  livenessProbe: {{- .Values.customLivenessProbe | toYaml | nindent 12 }}
  {{- else if .Values.livenessProbe.enabled }}
  livenessProbe:
    initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
    periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
    timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
    successThreshold: {{ .Values.livenessProbe.successThreshold }}
    failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
  {{- end }}
  {{- if .Values.customReadinessProbe }}
  readinessProbe: {{- .Values.customReadinessProbe | toYaml | nindent 12 }}
  {{- else if .Values.readinessProbe.enabled }}
  readinessProbe:
    initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
    periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
    timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
    successThreshold: {{ .Values.readinessProbe.successThreshold }}
    failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
  {{- end }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
