{{- if not .Values.warehouse.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radar-iceberg-catalog.warehouseSecret" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.warehouse.credentials.accessKeyKey }}: {{ .Values.warehouse.credentials.accessKey | quote }}
  {{ .Values.warehouse.credentials.secretKeyKey }}: {{ .Values.warehouse.credentials.secretKey | quote }}
{{- end }}
