{{- if ((.Values.podDisruptionBudget).enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-cp-ksql-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: cp-ksql-server
    release: {{ .Release.Name }}
spec:
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app: cp-ksql-server
      release: {{ .Release.Name }}
{{- end }}
