{{- if .Values.OPABridge.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iceberg-catalog.fullname" . }}-opa-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "iceberg-catalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: opa-bridge
type: Opaque
stringData:
  opa-config.yaml: |
    {{- toYaml .Values.OPABridge.opaConfig | nindent 4 }}
{{- end }}
