{{/*TODO alternative to hydra-clients-job - client ids and secrets in all the settings would need to be passed dynamically via secrets */}}
{{/*For now keeping as an alternative implementation */}}
{{- range $name, $client := .Values.oauth_clients }}
{{- if ne $client.enable false }}
---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: {{ $name | lower | replace "_" "-" }}-oauth-client
  namespace: default
spec:
  clientID: {{ $name | quote }}
  clientName: {{ $name | quote }}
  {{- if $client.grantTypes }}
  grantTypes:
    {{- range $client.grantTypes }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- if $client.responseTypes }}
  responseTypes:
    {{- range $client.responseTypes }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- if $client.scope }}
  scope: {{ if kindIs "string" $client.scope }}{{ $client.scope | quote }}{{ else }}{{ join " " $client.scope | quote }}{{ end }}
  {{- end }}
  {{- if $client.audience }}
  audience:
    {{- range $client.audience }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- if $client.redirectUris }}
  redirectUris:
    {{- range $client.redirectUris }}
    - {{ tpl . $ | quote }}
    {{- end }}
  {{- end }}
  {{- if $client.allowed_cors_origins }}
  allowedCORSOrigins:
    {{- range $client.allowed_cors_origins }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- if hasKey $client "skip_consent" }}
  skipConsent: {{ $client.skip_consent }}
  {{- end }}
  {{- if hasKey $client "skip_logout_consent" }}
  skipLogoutConsent: {{ $client.skip_logout_consent }}
  {{- end }}
  secretName: {{ $name | lower | replace "_" "-" }}-oauth-client
  tokenEndpointAuthMethod: {{ default "client_secret_basic" $client.tokenEndpointAuthMethod | quote }}
  hydraAdmin:
    url: http://radar-hydra-admin
    port: 4445
    endpoint: /admin/clients
    forwardedProto: http
{{- end }}
{{- end }}
