{{ range .Values.oauth_clients }}
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: {{ .name }}-oauth-client
  namespace: default
spec:
  clientName: {{ .name }}
  clientID: {{ .name }}
  grantTypes: {{ toYaml .grantTypes | nindent 4}}
  responseTypes: {{ toYaml .responseTypes | nindent 4}}
  scope: {{ .scope }}
  secretName: {{ .name }}-oauth-client
  redirectUris:
    {{- tpl (toYaml .redirectUris | nindent 4) $ -}}
{{/*   {{ toYaml .redirectUris | nindent 4}}*/}}
{{/*  postLogoutRedirectUris:*/}}
  audience: {{ toYaml .audience | nindent 4}}

  hydraAdmin:
    # if hydraAdmin is specified, all of these fields are required,
    # but they can be empty/0
    url: http://radar-hydra-admin
    port: 4445
    endpoint: /admin/clients
    forwardedProto: http
  tokenEndpointAuthMethod: client_secret_basic
{{end}}
---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: my-oauth2-client
  namespace: default
spec:
  clientID: my-oauth2-client
  clientName: my-oauth2-client
  grantTypes:
    - client_credentials
    - implicit
    - authorization_code
    - refresh_token
  responseTypes:
    - id_token
    - code
    - token
  scope: "read write"
  secretName: my-secret-123
  # these are optional
  redirectUris:
    - https://client/account
    - http://localhost:8080
  postLogoutRedirectUris:
    - https://client/logout
  audience:
    - audience-a
    - audience-b
  hydraAdmin:
    # if hydraAdmin is specified, all of these fields are required,
    # but they can be empty/0
    url: http://radar-hydra-admin
    port: 4445
    endpoint: /admin/clients
    forwardedProto: http
  tokenEndpointAuthMethod: client_secret_basic
