{{ range .Values.userGroups }}
apiVersion: nifi.konpyutaika.com/v1
kind: NifiUserGroup
metadata:
  name: {{ include "nifi-cluster.fullname" $ }}-{{ .name }}
spec:
  {{ if .identity }}
  identity: {{ .identity }}
  {{ end }}
  clusterRef:
    name: {{ include "nifi-cluster.fullname" $ }}
    namespace: {{ $.Release.Namespace }}
  usersRef:
{{ toYaml .users | indent 4 }}
  accessPolicies:
{{ toYaml .accessPolicies | indent 4 }}
---
{{ end }}