{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- $containerResourceAvailable := and (not (empty $kubeVersion)) (semverCompare ">=1.30.0" $kubeVersion) -}}
{{- if and .Values.deployment.autoscaling.enabled $containerResourceAvailable }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  name: {{ include "hydra.fullname" . }}
  labels:
    {{- include "hydra.labels" . | nindent 4 }}
spec:
  {{- with .Values.deployment.autoscaling.behavior }}
  behavior: {{- toYaml . | nindent 4 }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hydra.fullname" . }}
  minReplicas: {{ .Values.deployment.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.deployment.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.deployment.autoscaling.targetMemory }}
  - type: ContainerResource
    containerResource:
      name: memory
      container: {{ $.Chart.Name }}
      target:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.deployment.autoscaling.targetCPU}}
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ $.Chart.Name }}
      target:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- if not (empty .Values.deployment.autoscaling.extraMetrics) }}
  {{- toYaml .Values.deployment.autoscaling.extraMetrics | nindent 2 }}
  {{- end }}
{{- end }}
