# -- Deploy with minimal replicationFactor
dev_deployment: false

topic:
  partitions: 1
  replicationFactor: 3
  # http://kafka.apache.org/documentation/#topicconfigs
  config:
    cleanup.policy: compact

registry:
  name: confluent-schema-registry
  # -- Keep in sync with the version in the strimzi-registry-operator chart.
  spec:
    strimziVersion: v1beta2
    listener: tls
    securityProtocol: SSL

strimzi-registry-operator:
  clusterName: radar-kafka
  clusterNamespace: kafka
  operatorNamespace: kafka
