apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  radar.yml: |
    version: 1.0
    released: 2018-09-13
    {{- if .Values.zookeeper }}
    zookeeper:
        - host: {{ first (splitList ":" .Values.zookeeper) }}
          port: {{ last (splitList ":" .Values.zookeeper) }}
    {{- end }}
    broker:
        - host: {{ first (splitList ":" .Values.kafka) }}
          port: {{ last (splitList ":" .Values.kafka) }}
    schema_registry:
        - host: {{ (split ":" (trimPrefix "http://" .Values.schema_registry))._0 }}
          port: {{ (split ":" (trimPrefix "http://" .Values.schema_registry))._1 }}
          protocol: http
    {{- if .Values.rest_proxy }}
    rest_proxy:
        host: {{ (split ":" (trimPrefix "http://" .Values.rest_proxy))._0 }}
        port: {{ (split ":" (trimPrefix "http://" .Values.rest_proxy))._1 }}
        protocol:
    {{- end }}
    {{- tpl (toYaml .Values.config) . | nindent 4 }}
