{{- if eq .Values.user_repository_class "YamlUserRepository" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-users
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  fitbit-user.yml: |
  {{- range .Values.usersFile.users }}
    ---
    id: {{ .id }}
    projectId: {{ .projectId }}
    userId: {{ .userId }}
    sourceId: {{ .sourceId }}
    startDate: {{ .startDate }}
    endDate: {{ .endDate }}
    externalUserId: {{ .externalUserId }}
    {{- with .oauth2 }}
    oauth2:
      accessToken: {{ .accessToken }}
      refreshToken: {{ .refreshToken }}
      {{- if .expiresAt }}
      expiresAt: {{ .expiresAt }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
