apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: radar-fitbit-source
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    strimzi.io/cluster: {{ template "common.names.fullname" . }}
spec:
  class: org.radarbase.connect.rest.fitbit.FitbitSourceConnector
  tasksMax: {{ .Values.connector_num_tasks }}
