apiVersion: v2
appVersion: 0.12.2
dependencies:
- alias: postgresql
  condition: postgresql.enabled
  name: postgres
  repository: https://groundhog2k.github.io/helm-charts/
  version: 1.5.13
- alias: openfga
  condition: internalOpenFGA
  name: openfga
  repository: https://openfga.github.io/helm-charts
  version: 0.2.62
description: Helm Chart for Lakekeeper - a rust native Iceberg Rest Catalog
home: https://github.com/lakekeeper/lakekeeper
icon: https://raw.githubusercontent.com/lakekeeper/lakekeeper/refs/heads/main/site/docs/assets/bear.svg
keywords:
- lakekeeper
- iceberg
- catalog
- rest
- lakehouse
maintainers:
- name: Christian
  url: https://github.com/c-thiel
name: lakekeeper
type: application
version: 0.11.0
